"""initial schema — users, documents, chat_sessions, messages
    
Revision ID: 0001
Revises: 
Create Date: 2026-07-20    
    
WHY THIS EXISTS:
    Written by hand (not autogenerated) since this is the first migration introduced into a codebase
    that previously relied on db.create_all(). This version has been revised (pre-launch, before ever
    running against Neon) to fix issues found in review:
    - All timestamp columns are TIMESTAMP WITH TIME ZONE with a
    server-side default (`now()`), not just an app-level Python default —
    so timestamps are correct even for rows inserted outside the app
    (migration scripts, manual SQL, admin tooling).
  - chat_sessions.created_id renamed to created_at (was a naming bug).
  - documents gets a UNIQUE (user_id, filename) constraint — enforces the
    duplicate-upload guard at the DB level, closing a race condition that
    existed when it was purely an application-level check.
  - documents.filepath is nullable — the upload flow now creates the row
    first (to get its id for use as the canonical Chroma/R2 identifier),
    then fills in filepath once the storage upload succeeds.
  - Foreign keys use ON DELETE CASCADE so removing a user cleans up their
    documents/sessions/messages at the DB level, not just via the ORM. 
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_username", "users", ["username"])
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        # Nullable: row created before storage upload completes, so document.id exists to use as canonical
        # identifier for Chroma/R2 object key.
        sa.Column("filepath", sa.String(length=500), nullable=True),
        # Lifecycle: processing -> ready, or failed on ingestion failure.
        sa.Column("status", sa.String(length=20), nullable=False, server_default="processing"),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("user_id", "filename", name="uq_document_user_filename"),
    )
    op.create_index("ix_documents_user_id", "documents", ["user_id"])
    op.create_index("ix_documents_status", "documents", ["status"])
    
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_chat_sessions_user_id", "chat_sessions", ["user_id"])
    
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_messages_session_id", "messages", ["session_id"])
    

def downgrade():
    op.drop_index("ix_messages_session_id", table_name="messages")
    op.drop_table("messages")
    
    op.drop_index("ix_chat_sessions_user_id", table_name="chat_sessions")
    op.drop_table("chat_sessions")
    
    op.drop_index("ix_documents_user_id", table_name="documents")
    op.drop_index("ix_documents_status", table_name="documents")
    op.drop_table("documents")
    
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
    